name: Waka Readme
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
 
jobs:
  update-readme:
    name: Update this repo's README 
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          TIME_RANGE: last_30_days
          COMMIT_MESSAGE: Updated the Readme
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          SHOW_TOTAL: true
          SHOW_TIME: false
