name: Waka Readme
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
 
jobs:
  update-readme:
    name: Update this repo's README 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hugh-zhan9/hugh-zhan9@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
